CREATE DATABASE Team10
GO

USE Team10
GO

CREATE TABLE users (
    id BIGINT IDENTITY(1,1) PRIMARY KEY,
    full_name NVARCHAR(100),
    email NVARCHAR(150) UNIQUE NOT NULL,
    password NVARCHAR(255) NOT NULL,
    role NVARCHAR(50) NOT NULL
);




/*		
	   ALTER DATABASE [Team10]
      SET SINGLE_USER
      WITH ROLLBACK IMMEDIATE;
    -- now we’re safe to drop
    DROP DATABASE [Team10];
	GO
	*/